[Materials.Steel]
name = "Steel"
rho = 7810.0
E = 211000000000.0
G_s = 81200000000.0
Poisson = 0.2992610837438423
color = "#525252"

[Materials.AISI4140]
name = "AISI4140"
rho = 7850.0
E = 203200000000.0
G_s = 80000000000.0
Poisson = 0.27
color = "#525252"

[Materials.A216WCB]
name = "A216WCB"
rho = 7820.0
E = 210000000000.0
G_s = 81395348837.2093
Poisson = 0.29000000000000004
color = "#525252"
